<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbfIH77\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbfIH77/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKbfIH77.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKbfIH77\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKbfIH77\App_KernelDevDebugContainer([
    'container.build_hash' => 'KbfIH77',
    'container.build_id' => '3deb7756',
    'container.build_time' => 1677805906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbfIH77');
