<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'display_liste' => [[], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['text', '/afficherart']], [], [], []],
    'addarticle' => [[], ['_controller' => 'App\\Controller\\ArticleController::addart'], [], [['text', '/addarticle']], [], [], []],
    'supp' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::deleteart'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/supprimerart']], [], [], []],
    'modifierarticle' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::modifierarticle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifierarticle']], [], [], []],
    'front' => [[], ['_controller' => 'App\\Controller\\ArticleController::base'], [], [['text', '/']], [], [], []],
    'rec_liste' => [[], ['_controller' => 'App\\Controller\\ReclamationController::index'], [], [['text', '/afficherrec']], [], [], []],
    'addrecl' => [[], ['_controller' => 'App\\Controller\\ReclamationController::addreclamation'], [], [['text', '/addrecl']], [], [], []],
    'supprec' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::deleterec'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/supprimerrec']], [], [], []],
    'modifierrec' => [['id'], ['_controller' => 'App\\Controller\\ReclamationController::modifierrec'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifierrec']], [], [], []],
    'rec_listeadm' => [[], ['_controller' => 'App\\Controller\\ReclamationController::listadm'], [], [['text', '/afficherrecadm']], [], [], []],
    'frt' => [[], ['_controller' => 'App\\Controller\\ReclamationController::frt'], [], [['text', '/frt']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
